DROP TABLE IF EXISTS T_USER;

CREATE TABLE IF NOT EXISTS T_USER_US (
  US_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  US_LOGIN VARCHAR(40) UNIQUE NOT NULL,
  US_SEQ VARCHAR(8) NOT NULL,
  US_MAIL VARCHAR(254) NOT NULL,
  US_FNAME VARCHAR(40) NOT NULL,
  US_NAME VARCHAR(40) NOT NULL,
  US_PASSW VARCHAR(256) NOT NULL
);
